### ISSUE TITLE
Kali Not Working 

### ISSUE THREAD

**Issue by fb11** [diljith369/AvBuster#1]
This program does not work well.
exe not created
<img width="324" alt="ekran resmi 2018-02-28 15 54 33" src="https://user-images.githubusercontent.com/11415252/36788639-c1d8d60c-1c9f-11e8-8ebf-9dd445df68ed.png">

<img width="305" alt="ekran resmi 2018-02-28 15 52 11" src="https://user-images.githubusercontent.com/11415252/36788564-75b11ff0-1c9f-11e8-865a-6a8fb861c5d0.png">

**Comment by diljith369** [comment]
Sorry bro , currently designed in a way to work with windows only (knocker.exe) I am working on this now will make it work for linux too . Thanks for reporting . I will make it soon working in Linux .

**Comment by diljith369** [comment]
Issue resolved . knocker server now runs in Linux too. :)
